"""empty message

Revision ID: fb869b731e2d
Revises: 212126bbbc3b
Create Date: 2023-05-20 14:55:24.228954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb869b731e2d'
down_revision = '212126bbbc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_name', sa.Text(), nullable=True))
        batch_op.drop_constraint('pantry_ingredient_id_fkey', type_='foreignkey')
        batch_op.drop_column('ingredient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pantry_ingredient_id_fkey', 'ingredients', ['ingredient_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('ingredient_name')

    # ### end Alembic commands ###
